-
  name: 'SSO session destroy'
  uriPattern: 'session/{sessionId}/destroy'
  defaults:
    '@package':    'Flowpack.SingleSignOn.Client'
    '@controller': 'Session'
    '@action':     'destroy'
    '@format':     'json'

-
  name: 'SSO authentication callback'
  uriPattern: 'authentication/callback'
  defaults:
    '@package':    'Flowpack.SingleSignOn.Client'
    '@controller': 'Authentication'
    '@action':     'callback'
    '@format':     'html'
